# Site settings
title: Dausha Publishing
email: dausha@gmail.com
description: "Dausha Publishing is the website for Ben Wilson, author of the Postal Marine Series."
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://dausha.net" # the base hostname & protocol for your site
url: ""
twitter_username: merovex
github_username:  merovex
category_dir: /
# permalink: /p/:title
permalink: /:categories/:title

# Build settings
markdown: kramdown

paginate: 7          # Posts per page on the blog index
# paginate_path: "p/:num"
# pagination_dir: "/"
recent_posts: 7       # Posts in the sidebar Recent Posts section
popular_posts_count: 7

gems:
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - _config.yml
  - _sass
  - _site
  - _data
  - config
  - config.ru

## Site Specific
cdn_url: https://s3.amazonaws.com/dausha

social_amazon: http://amzn.to/1VwV58V
social_facebook: http://on.fb.me/1M3gSiz
social_feed: http://bit.ly/1Lrbjf0