# Site settings
title: Merovex Press
email: dausha@gmail.com
description: "Merovex Press is the website for Ben Wilson, author of the Postal Marine Series."
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://dausha.net" # the base hostname & protocol for your site
url: http://www.dausha.net
author: Ben Wilson
twitter_username: merovex
github_username:  merovex
google_plus_id: BenWilsonAuthor
category_dir: /
permalink: /:categories/:title/
subscribe_rss: /atom.xml

# theme: merovex

location:
  city: Arlington
  state: Virginia
  country: United States of America

# Build settings
markdown: kramdown
kramdown:
  # enable_coderay: true
  syntax_highlighter: rouge

paginate: 12          # Posts per page on the blog index
paginate_path: "/blog/page:num"
recent_posts: 9       # Posts in the sidebar Recent Posts section
popular_posts_count: 9
sass:
    sass_dir: _sass
gems:
  - jekyll-sitemap
  - coderay
  - jekyll-paginate
  # - jemoji
  # - jekyll-mentions
  # - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - _config.yml
  - _site
  - _data
  - config.ru
  - vendor
  - .sublime-workspace

## Site Specific
# cdn_url: https://s3.amazonaws.com/dausha
cdn_url: http://d1czp97ry8if6j.cloudfront.net

collections:
  books:
    output: true
    permalink: /books/:path/

summary:
  writing: "Writing describes my thoughts about the craft of writing."
  diary: "The Diary are things going on in my writing or life that I just felt like sharing."
  postal marine series: "Stuff."
  technology: "Technology covers my thoughts on technology, either writing or otherwise."
  vw beetle: "The VW Beetle category covers my personal interest in an iconic automobile."

defaults:
  -
    scope:
      path: ""
      type: "books"
    values:
      layout: book
      featured: false
      hidden: false
      variant: false
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: Ben Wilson
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: post
      author: Ben Wilson

social_amazon: http://amzn.to/1VwV58V
social_facebook: http://on.fb.me/1M3gSiz
social_feed: http://bit.ly/1Lrbjf0

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_page: "Ben-Wilson-Author-143743165675224"
    fb_image: "https://s3.amazonaws.com/dausha/images/apple-touch-icon-120x120.png"
    fb_app_id: "974042092652489"
    fb_image_width: 300
    fb_image_height: 300
    fb_image_type: "image/jpg"

    twitter_image: "assets/logo.png"

    os_repo: "https://github.com/RichardLitt/wordhoardpress.com"
    os_rcs_type: "git"
    os_src: "git@github.com:RichardLitt/wordhoardpress.com.git"