#----------------------------------------
# Site settings
#----------------------------------------
theme                     : merovex

title                     : Merovex Press
description               : Merovex Press is the website for Ben Wilson, author of the Postal Marine Series.
baseurl                   : "" 
url                       : http://www.dausha.net
cdn_url                   : https://d1czp97ry8if6j.cloudfront.net

#----------------------------------------
# Site Author
#----------------------------------------
author:
  name                    : "Ben Wilson"
  avatar                  : "/assets/images/bio-photo.jpg"
  bio                     : "I am an amazing person."
  location                : "Somewhere"
  email                   : "dausha@gmail.com"
  uri                     :
  bitbucket               :
  codepen                 :
  dribbble                :
  flickr                  :
  facebook                :
  foursquare              :
  github                  :
  google_plus             : BenWilsonAuthor
  keybase                 :
  instagram               :
  lastfm                  :
  linkedin                :
  pinterest               :
  soundcloud              :
  stackoverflow           : # "123456/username" (the last part of your profile url, e.g. http://stackoverflow.com/users/123456/username)
  steam                   :
  tumblr                  :
  twitter                 : merovex
  vine                    :
  weibo                   :
  xing                    :
  youtube                 :

subscribe_rss             : /atom.xml

#----------------------------------------
# Blog Category
#----------------------------------------
category_dir              : /
permalink                 : /:categories/:title/

#----------------------------------------
# Social Sharing
#----------------------------------------

#----------------------------------------
# SEO Related
#----------------------------------------
google_site_verification  :
bing_site_verification    :
alexa_site_verification   :
yandex_site_verification  :

#----------------------------------------
# Build settings
# - Conversion
# - Markdown Processing
#----------------------------------------

# highlighter               : rouge
markdown                  : kramdown
lsi                       : false
excerpt_separator         : "\n\n"
incremental               : false

# Markdown Processing
kramdown:
  input                   : GFM
  hard_wrap               : false
  auto_ids                : true
  footnote_nr             : 1
  entity_output           : as_char
  toc_levels              : 2..4
  smart_quotes            : lsquo,rsquo,ldquo,rdquo
  syntax_highlighter_opts:
    disable               : true

#----------------------------------------
# Analytics
#----------------------------------------
analytics:
  provider                : false # false (default), "google", "google-universal", "custom"
  google:
    tracking_id           :

#----------------------------------------
# Collections
#----------------------------------------
collections:
  books:
    output: true
    permalink: /korektu/:path/
  writing-tips:
    output: true
    permalink: /:collection/:path/
  writing-a-novel-series:
    output: false
    permalink: /wans/:path/
  sales-charts:
    output: true
    permalink: /sales/:path/
  writing-logs:
    output: true
    permalink: /:collection/:path/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author_profile: true
      read_time: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      author_profile: true
  -
    scope:
      path: ""
      type: "books"
    values:
      layout: korektu
      featured: false
      hidden: false
      variant: false
      recaptcha: true
      editions:
        - Alpha
        - Beta
  -
    scope:
      path: ""
      type: "writing-a-novel-series"
    values:
      layout: page
  -
    scope:
      path: ""
      type: "writing-tips"
    values:
      layout: page
  -
    scope:
      path: ""
      type: "sales-charts"
    values:
      layout: sales-chart
  -
    scope:
      path: ""
      type: "writing-logs"
    values:
      layout: writing-progress-chart
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: Ben Wilson
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: post
      author: Ben Wilson

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - "*.json"
  - .travis.yml
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

#----------------------------------------
# Plugins
#----------------------------------------
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
