# Site settings
title: Merovex Press
email: dausha@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Merovex Press is the website for Ben Wilson, author of the Postal Marine Series.
description: ""
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://dausha.net" # the base hostname & protocol for your site
url: http://www.dausha.net
author: Ben Wilson
twitter_username: merovex

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

include: ["_pages"]
cdn_url: https://d1czp97ry8if6j.cloudfront.net

theme: merovex
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

url: http://www.dausha.net
author: Ben Wilson
twitter_username: merovex
google_plus_id: BenWilsonAuthor
category_dir: /
permalink: /:categories/:title/
subscribe_rss: /atom.xml

location:
  city: Arlington
  state: Virginia
  country: United States of America

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter_opts:
    disable: true



collections:
  books:
    output: true
    permalink: /korektu/:path/
  writing-tips:
    output: true
    permalink: /writing-tips/:path/
  writing-a-novel-series:
    output: false
    permalink: /wans/:path/
  sales-charts:
    output: true
    permalink: /sales/:path/
  writing-logs:
    output: true
    permalink: /writing-logs/:path/

summary:
  writing: "Writing describes my thoughts about the craft of writing."
  diary: "The Diary are things going on in my writing or life that I just felt like sharing."
  postal marine series: "Stuff."
  technology: "Technology covers my thoughts on technology, either writing or otherwise."
  vw beetle: "The VW Beetle category covers my personal interest in an iconic automobile."

defaults:
  -
    scope:
      path: ""
      type: "books"
    values:
      layout: korektu
      featured: false
      hidden: false
      variant: false
      recaptcha: true
      editions:
        - Alpha
        - Beta
  -
    scope:
      path: ""
      type: "writing-a-novel-series"
    values:
      layout: page
  -
    scope:
      path: ""
      type: "writing-tips"
    values:
      layout: page
  -
    scope:
      path: ""
      type: "sales-charts"
    values:
      layout: sales-chart
  -
    scope:
      path: ""
      type: "writing-logs"
    values:
      layout: writing-progress-chart
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: Ben Wilson
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: post
      author: Ben Wilson