# Site settings
title: Dausha Publishing
email: dausha@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://dausha.net" # the base hostname & protocol for your site
url: ""
twitter_username: merovex
github_username:  merovex
permalink: /p/:title

# Build settings
markdown: kramdown
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..3
  use_coderay: false
  parse_block_html: false


paginate: 6          # Posts per page on the blog index
paginate_path: "p/:num"
pagination_dir: "p"
recent_posts: 6       # Posts in the sidebar Recent Posts section
excerpt_link: "Read the full article →"  # "Continue reading" link text at the bottom of excerpted articles
popular_posts_count: 6

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - _config.yml
  - _sass
  - _site
  - config
  - config.ru

## Site Specific
cdn_url: https://s3.amazonaws.com/dausha

social_amazon: http://amzn.to/1VwV58V
social_facebook: http://on.fb.me/1M3gSiz
social_feed: http://bit.ly/1Lrbjf0