# Site settings
title: Dausha Publishing
email: dausha@gmail.com
description: "Dausha Publishing is the website for Ben Wilson, author of the Postal Marine Series."
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://dausha.net" # the base hostname & protocol for your site
url: http://www.dausha.net
author: Ben Wilson
twitter_username: merovex
github_username:  merovex
category_dir: /
# permalink: /p/:title
permalink: /:categories/:title
# permalink: /articles/:title
subscribe_rss: /atom.xml
# Build settings
markdown: kramdown
kramdown:
  use_coderay: true

paginate: 6          # Posts per page on the blog index
# paginate_path: "p/:num"
# pagination_dir: "/"
recent_posts: 6       # Posts in the sidebar Recent Posts section
popular_posts_count: 6

# jekyll-archives: 
#   enabled: 
#     - categories
#     - tags
#   layout: 'archive'
#   permalinks:
#     category: '/category/:name/'
#     tag: '/tag/:name/'

gems:
  - jekyll-sitemap
  - coderay

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - _config.yml
  - _sass
  - _site
  - _data
  - config
  - config.ru

## Site Specific
cdn_url: https://s3.amazonaws.com/dausha

social_amazon: http://amzn.to/1VwV58V
social_facebook: http://on.fb.me/1M3gSiz
social_feed: http://bit.ly/1Lrbjf0

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "https://s3.amazonaws.com/dausha/images/apple-touch-icon-120x120.png"
    fb_image_width: 600
    fb_image_height: 360
    fb_image_type: "image/jpg"

    twitter_image: "assets/logo.png"

    os_repo: "https://github.com/RichardLitt/wordhoardpress.com"
    os_rcs_type: "git"
    os_src: "git@github.com:RichardLitt/wordhoardpress.com.git"