cp -R ../dausha-publishing-old/source/404.markdown .
cp -R ../dausha-publishing-old/source/CNAME .
cp -R ../dausha-publishing-old/source/PostalMarineSeriesChronology.pdf .
cp -R ../dausha-publishing-old/source/a11y .
cp -R ../dausha-publishing-old/source/a11y-maturity-model .
cp -R ../dausha-publishing-old/source/amcharts .
cp -R ../dausha-publishing-old/source/aria .
cp -R ../dausha-publishing-old/source/astro-empires .
cp -R ../dausha-publishing-old/source/b .
cp -R ../dausha-publishing-old/source/bf .
cp -R ../dausha-publishing-old/source/blog .
cp -R ../dausha-publishing-old/source/book .
cp -R ../dausha-publishing-old/source/bookmaker .
cp -R ../dausha-publishing-old/source/books.html .
cp -R ../dausha-publishing-old/source/clash-of-clans .
cp -R ../dausha-publishing-old/source/dc .
cp -R ../dausha-publishing-old/source/evernote .
cp -R ../dausha-publishing-old/source/favicon.png .
cp -R ../dausha-publishing-old/source/four-chords .
cp -R ../dausha-publishing-old/source/furlong-firkin-fortnight-system .
cp -R ../dausha-publishing-old/source/lawn-calendar .
cp -R ../dausha-publishing-old/source/moral-premise .
cp -R ../dausha-publishing-old/source/nova-beetle-project .
cp -R ../dausha-publishing-old/source/password .
cp -R ../dausha-publishing-old/source/process .
cp -R ../dausha-publishing-old/source/pub .
cp -R ../dausha-publishing-old/source/r .
cp -R ../dausha-publishing-old/source/resources .
cp -R ../dausha-publishing-old/source/sales .
cp -R ../dausha-publishing-old/source/savage-worlds .
cp -R ../dausha-publishing-old/source/scrivener-tips .
cp -R ../dausha-publishing-old/source/snippets .
cp -R ../dausha-publishing-old/source/spacecraft-design .
cp -R ../dausha-publishing-old/source/stylesheets .
cp -R ../dausha-publishing-old/source/subscribe .
